### ISSUE TITLE
Unsaved changes functionality on Evaluation page

### ISSUE THREAD

**Issue by uoa-ypec413** [uoa-ypec413/metacodenition#74]
For the Evaluation Page, add unsaved changes functionality. When a user makes changes and has not saved them, make sure to notify them when they try to navigate away from the page. Change the "Submit" button to "Save"

**Comment by kand198** [comment]
Do we need some way of ensuring all changes are saved when navigating away from the implementing a solution page as well? I'm always terrified that changes won't persist to local cache haha.

**Comment by uoa-ypec413** [comment]
> Do we need some way of ensuring all changes are saved when navigating away from the implementing a solution page as well? I'm always terrified that changes won't persist to local cache haha.

I don't think so? What really is the likelihood that local storage fails? I haven't seen it yet

**Comment by kand198** [comment]
I think it's more that there is propogation delay in the pipeline:
User makes change -> onChange event is fired -> useEffect hook is called -> changes are persisted to localstorage

Idk if its a concern but is there harm in checking when a user tries to navigate away? Idk how we would even do this tbh. Just something to think about.

**Comment by kand198** [comment]
At the moment I am thinking that DoD should include:
- [ ] Tracking when a user has unsaved changes on any page
- [ ] Disabling save buttons when there are no unsaved changes
- [ ] Notifying the user when they try to navigate away from pages with unsaved changes
