### ISSUE TITLE
Bug: Running test cases after incorrect formatting 

### ISSUE THREAD

**Issue by uoa-ypec413** [uoa-ypec413/metacodenition#77]
3/15 test cases failed though none failed - incorrect formatting then run it and run it again without

**Comment by kand198** [comment]
I have found the issue...

If you create your own custom test case, and it is selected when deleted, it is not deleted from the "selected" list. This means that when you click the "run button" then they are still run through code runner.

This should be an easy fix. Additionally, we should create a "warning" notification type, and create warning notifications if the user clicks run when no test cases are selected.
